from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
font = QtGui.QFont()
font.setPointSize(12)
centralwidget.setFont(font)
centralwidget.setObjectName("centralwidget")
History = QtWidgets.QTextBrowser(parent=centralwidget)
History.setGeometry(QtCore.QRect(30, 180, 481, 211))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
History.setFont(font)
History.setObjectName("History")
Parking = QtWidgets.QTextBrowser(parent=centralwidget)
Parking.setGeometry(QtCore.QRect(530, 180, 301, 211))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
Parking.setFont(font)
Parking.setObjectName("Parking")
ExitEntryBtn = QtWidgets.QPushButton(parent=centralwidget)
ExitEntryBtn.setGeometry(QtCore.QRect(30, 80, 221, 51))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
font.setBold(True)
font.setWeight(75)
ExitEntryBtn.setFont(font)
ExitEntryBtn.setObjectName("ExitEntryBtn")
Label = QtWidgets.QLabel(parent=centralwidget)
Label.setGeometry(QtCore.QRect(30, 30, 501, 41))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
font.setBold(True)
font.setWeight(75)
Label.setFont(font)
Label.setObjectName("Label")
NewEmployeeBtn = QtWidgets.QPushButton(parent=centralwidget)
NewEmployeeBtn.setGeometry(QtCore.QRect(290, 80, 391, 51))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
font.setBold(True)
font.setWeight(75)
NewEmployeeBtn.setFont(font)
NewEmployeeBtn.setObjectName("NewEmployeeBtn")
GuestsList = QtWidgets.QTextBrowser(parent=centralwidget)
GuestsList.setGeometry(QtCore.QRect(30, 440, 481, 221))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
GuestsList.setFont(font)
GuestsList.setObjectName("GuestsList")
label_2 = QtWidgets.QLabel(parent=centralwidget)
label_2.setGeometry(QtCore.QRect(40, 150, 231, 21))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
label_2.setFont(font)
label_2.setObjectName("label_2")
label_3 = QtWidgets.QLabel(parent=centralwidget)
label_3.setGeometry(QtCore.QRect(40, 410, 151, 21))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
label_3.setFont(font)
label_3.setObjectName("label_3")
label_4 = QtWidgets.QLabel(parent=centralwidget)
label_4.setGeometry(QtCore.QRect(530, 150, 211, 21))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
label_4.setFont(font)
label_4.setObjectName("label_4")
label_5 = QtWidgets.QLabel(parent=centralwidget)
label_5.setGeometry(QtCore.QRect(530, 410, 211, 21))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
label_5.setFont(font)
label_5.setObjectName("label_5")
EmployeeList = QtWidgets.QTextBrowser(parent=centralwidget)
EmployeeList.setGeometry(QtCore.QRect(530, 440, 301, 221))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
EmployeeList.setFont(font)
EmployeeList.setObjectName("EmployeeList")

ExitEntryBtn.setText("Записать вход/выход")
Label.setText("Система управления контрольно пропускного пункта")
NewEmployeeBtn.setText("Зарегистрировать пропуск сотрудника")
label_2.setText("История посещений:")
label_3.setText("Гости:")
label_4.setText("Парковочные места:")
label_5.setText("Сотрудники:")