from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
font = QtGui.QFont()
font.setPointSize(12)
centralwidget.setFont(font)
centralwidget.setObjectName("centralwidget")
Label = QtWidgets.QLabel(parent=centralwidget)
Label.setGeometry(QtCore.QRect(60, 0, 451, 71))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(16)
font.setBold(True)
font.setWeight(75)
Label.setFont(font)
Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
Label.setObjectName("Label")
NameEntry = QtWidgets.QLineEdit(parent=centralwidget)
NameEntry.setGeometry(QtCore.QRect(140, 70, 181, 31))
NameEntry.setObjectName("NameEntry")
Label_2 = QtWidgets.QLabel(parent=centralwidget)
Label_2.setGeometry(QtCore.QRect(20, 70, 111, 31))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(14)
font.setBold(True)
font.setWeight(75)
Label_2.setFont(font)
Label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Label_2.setObjectName("Label_2")
Label_3 = QtWidgets.QLabel(parent=centralwidget)
Label_3.setGeometry(QtCore.QRect(20, 130, 111, 31))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(14)
font.setBold(True)
font.setWeight(75)
Label_3.setFont(font)
Label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
Label_3.setObjectName("Label_3")
SecondNameEntry = QtWidgets.QLineEdit(parent=centralwidget)
SecondNameEntry.setGeometry(QtCore.QRect(140, 130, 181, 31))
SecondNameEntry.setObjectName("SecondNameEntry")
Submit = QtWidgets.QPushButton(parent=centralwidget)
Submit.setGeometry(QtCore.QRect(220, 190, 121, 31))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(14)
font.setBold(True)
font.setWeight(75)
Submit.setFont(font)
Submit.setObjectName("Submit")
Error1 = QtWidgets.QLabel(parent=centralwidget)
Error1.setGeometry(QtCore.QRect(70, 50, 321, 21))
palette = QtGui.QPalette()
brush = QtGui.QBrush(QtGui.QColor(217, 0, 0))
brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
brush = QtGui.QBrush(QtGui.QColor(217, 0, 0))
brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
Error1.setPalette(palette)
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(10)
Error1.setFont(font)
Error1.setObjectName("Error1")
Error2 = QtWidgets.QLabel(parent=centralwidget)
Error2.setGeometry(QtCore.QRect(70, 110, 321, 21))
palette = QtGui.QPalette()
brush = QtGui.QBrush(QtGui.QColor(217, 0, 0))
brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
brush = QtGui.QBrush(QtGui.QColor(217, 0, 0))
brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
Error2.setPalette(palette)
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(10)
Error2.setFont(font)
Error2.setObjectName("Error2")
Confirm = QtWidgets.QRadioButton(parent=centralwidget)
Confirm.setGeometry(QtCore.QRect(60, 170, 471, 18))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
font.setBold(True)
font.setWeight(75)
Confirm.setFont(font)
Confirm.setObjectName("Confirm")

Label.setText("Регистрация нового сотрудника")
Label_2.setText("Имя:")
Label_3.setText("Фамилия:")
Submit.setText("Ввод")
Error1.setText("*Поле не заполнено/заполнено неправильно")
Error2.setText("*Поле не заполнено/заполнено неправильно")
Confirm.setText("Подтверждаю правильность введенных данных")